# Generated by Django 4.2.5 on 2023-09-21 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('hours_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('day_of_week', models.PositiveIntegerField()),
                ('start_time_local', models.TimeField()),
                ('end_time_local', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone_str', models.CharField(max_length=100)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreStatus',
            fields=[
                ('status_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('timestamp_utc', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['store_id'], name='store_store_store_i_9d4d62_idx'),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
        migrations.AddIndex(
            model_name='timezone',
            index=models.Index(fields=['store'], name='store_timez_store_i_34568d_idx'),
        ),
        migrations.AddIndex(
            model_name='storestatus',
            index=models.Index(fields=['store'], name='store_store_store_i_57e980_idx'),
        ),
        migrations.AddIndex(
            model_name='businesshours',
            index=models.Index(fields=['store'], name='store_busin_store_i_be6426_idx'),
        ),
    ]
